name: Shopify App Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker image 
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker build -t shailendratrivedi009/new_docker_shopify:latest .
          docker push shailendratrivedi009/new_docker_shopify:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull shailendratrivedi009/new_docker_shopify:latest
      - name: Delete old container
        run: docker rm -f new_docker_shopify-container || true
      - name: Run docker container
        run: docker run -d -p 9091:9091 --name new_docker_shopify-container shailendratrivedi009/new_docker_shopify:latest
